language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra
    # SDK Version to compile project
    - android-26
    - android-23
    
before_install:
    - git clone --depth 1 https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
    - export ANDROID_NDK_HOME=$HOME/android-ndk-root
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        
script: ./gradlew build

#deploy:
#  provider: releases
#  api_key:
#    secure: "edfe2a84922e51bd9f23abde335126454d1f9841"
#  file: "app/build/outputs/apk/app*release*.apk"
#  file_glob: "true"
#  skip_cleanup: true
#  on:
#    branch: master
#    repo: trongvu/ATCommander
