/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "mosquitto_callback_wrapper.h"
/* Header for class com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper */

#ifndef _Included_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
#define _Included_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
#ifdef __cplusplus
extern "C" {

class mosquitto_callback_wrapper *jni_mosquitto;
#endif
/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    connect
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_connect
        (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    reconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_reconnect
        (JNIEnv *, jobject);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_disconnect
        (JNIEnv *, jobject);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    publish
 * Signature: (ILjava/lang/String;I[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_publish
        (JNIEnv *, jobject, jint, jstring, jstring, jint, jboolean);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    subscribe
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_subscribe
        (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    unsubscribe
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_unsubscribe
        (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    loop
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_loop
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_release
        (JNIEnv *, jobject);

/*
 * Class:     com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper
 * Method:    register
 * Signature: (Ljava/lang/String)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_trongvu_mosquittomqtt_wrapper_MosquittoWrapper_init
        (JNIEnv *env, jobject obj, jstring id);
#ifdef __cplusplus
}
#endif
#endif
